/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [16-1:0] M_ad_out;
  wire [1-1:0] M_ad_z;
  wire [1-1:0] M_ad_v;
  wire [1-1:0] M_ad_n;
  reg [8-1:0] M_ad_io_dip;
  reg [16-1:0] M_ad_a;
  reg [16-1:0] M_ad_b;
  add_1 ad (
    .io_dip(M_ad_io_dip),
    .a(M_ad_a),
    .b(M_ad_b),
    .out(M_ad_out),
    .z(M_ad_z),
    .v(M_ad_v),
    .n(M_ad_n)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_ad_a = io_dip[0+7-:8];
    M_ad_b = io_dip[8+7-:8];
    M_ad_io_dip = io_dip[16+7-:8];
    io_led[8+7-:8] = M_ad_out[0+7-:8];
    io_led[16+7-:8] = M_ad_out[8+7-:8];
    io_led[0+0+0-:1] = M_ad_z;
    io_led[0+1+0-:1] = M_ad_v;
    io_led[0+2+0-:1] = M_ad_n;
  end
endmodule
