/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_1 (
    input [15:0] a,
    input [15:0] b,
    input [7:0] io_dip,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (io_dip[0+7-:8])
      5'h18: begin
        out = a & b;
      end
      5'h1e: begin
        out = a | b;
      end
      5'h16: begin
        out = a ^ b;
      end
      3'h4: begin
        out = a ~^ b;
      end
      5'h1a: begin
        out = a;
      end
    endcase
  end
endmodule
