/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module add_1 (
    input [7:0] io_dip,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] hold;
  
  always @* begin
    if (io_dip[0+0-:1] == 1'h0) begin
      hold = a + b;
    end else begin
      hold = a - b;
    end
    out = hold[0+15-:16];
    if (hold == 1'h0) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    v = ((io_dip[7+0-:1] ^ a[15+0-:1]) & (io_dip[7+0-:1] ^ b[15+0-:1]) & ~hold[15+0-:1] | (~(io_dip[7+0-:1] ^ b[15+0-:1]) & hold[15+0-:1]));
    n = hold[15+0-:1];
  end
endmodule
